# Complementing a Strand of DNA
# https://rosalind.info/problems/rvco/

from Bio import SeqIO
from Bio.Seq import Seq
import io

fasta_str = """
>Rosalind_0732
GCGATGCTTTCGTTCGGGGCTGTCACTTGGGCATTGGTGCAAGATTTAGTTTAACATCGT
CAAGAGTCTTATTTACGAGATACGATGCGT
>Rosalind_8154
CCGATTCATGCATGGGTCTTCGAGGGGATCGCATTGCAATGCTCGGGAATAACACAGTGT
TTTAAATTTGGTTTCGCTGTATAGGGGGGCAATAGGTCAT
>Rosalind_2098
GGGAGAGTGTAAGATTTATTGCTCGCATCCGGCCCTCTCACCAGGTAAGTCTACACGGGC
AGCCACGGTGGGTTGCGGTTGGAACTTC
>Rosalind_1885
GAAGCTCCCATAGCATTTGAAGTCGACGCTTTTGGGTAAGCGCTAAAGCTTTAGCGCTTA
CCCAAAAGCGTCGACTTCAAATGCTATGGGAGCTTC
>Rosalind_4221
GGAACGAGTGGCTTTGTAAGGAATGAGTGCACATATGTGTAGGCTAACCGATTTATTCAG
CTCTCTTCCCCGCGATCCTAGGCACGTGGCTAATTG
>Rosalind_7971
AGCCATCCTATCGAGCAGGGCAGGACGCCAATGAAGAGGACAGCAACCGCCCATTGCGAC
GTCGGTGGAAGTTACTGGAG
>Rosalind_0478
CGGTTGTATGTGCGGCTACCGAGTAGCATCAACTTGGGTGCTAGCACCCAAGTTGATGCT
ACTCGGTAGCCGCACATACAACCG
>Rosalind_4754
TAGGTCCAGTAACAAACGTTACGTTTGAGCCCATAAGGCGAGCGATGACAGGAGCATAGC
CCTCCGGAAGAGAGGACGCCGAAGGGTATATCCG
>Rosalind_4106
TCGAATTGAACGCCATCAGCTCCGCGTCGGATGCGGAATGCATTCGATCGAATGCATTCC
GCATCCGACGCGGAGCTGATGGCGTTCAATTCGA
>Rosalind_4627
GGGGTTCATCACGTGAGAGCTCCAAGGCGTAACCTGTTTCGAAACAGGTTACGCCTTGGA
GCTCTCACGTGATGAACCCC
"""

records = list(SeqIO.parse(io.StringIO(fasta_str), "fasta"))

count = 0
for record in records:
    seq = record.seq
    if seq == seq.reverse_complement():
        count += 1

print(count)
